package main

const (
	STATS_FILE = "./exporterStats"

	ULIEGE_PEN_IANA = 10383
	TEMPLATE_ID     = 293 // Must be higher than 255 (arbitrary)
	IPFIX_DOMAIN_ID = 1

	IOAM6_GENL_NAME       string = "IOAM6"
	IOAM6_GENL_GROUP_NAME string = "ioam6_events"

	IOAM6_EVENT_TYPE_TRACE = 1

	IOAM6_EVENT_ATTR_TRACE_NAMESPACE = 1
	IOAM6_EVENT_ATTR_TRACE_NODELEN   = 2
	IOAM6_EVENT_ATTR_TRACE_TYPE      = 3
	IOAM6_EVENT_ATTR_TRACE_DATA      = 4

	TRACE_TYPE_BIT0_MASK  = 1 << 23
	TRACE_TYPE_BIT1_MASK  = 1 << 22
	TRACE_TYPE_BIT2_MASK  = 1 << 21
	TRACE_TYPE_BIT3_MASK  = 1 << 20
	TRACE_TYPE_BIT4_MASK  = 1 << 19
	TRACE_TYPE_BIT5_MASK  = 1 << 18
	TRACE_TYPE_BIT6_MASK  = 1 << 17
	TRACE_TYPE_BIT7_MASK  = 1 << 16
	TRACE_TYPE_BIT8_MASK  = 1 << 15
	TRACE_TYPE_BIT9_MASK  = 1 << 14
	TRACE_TYPE_BIT10_MASK = 1 << 13
	TRACE_TYPE_BIT22_MASK = 1 << 1
)
